version: "3"
services:
  apache:
    build: .
    ports:
      - 8888:80
    links:
      - mysql
    volumes:
      - ./source/:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./bashrc:/var/www/.bashrc

  mysql:
    image: mysql:8.0
    ports:
      - 8889:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app123
    volumes:
      - db:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    restart: always
    #ports:
    #  - '6379:6379'

volumes:
  db:
