version: "3"
services:
  apache:
    build: .
    ports:
      - 8888:80
    links:
      - mysql
    volumes:
      - ./source/:/var/www/html
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
  mysql:
    image: mysql:8.0
    ports:
      - 8889:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app123

